name: Update Server

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        timeout-minutes: 20
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 20m
          script: |
            # Exit immediately if a command exits with a non-zero status.
            set -e

            # Define variables for maintainability
            APP_DIR=./cojudge.cloud
            REPO_URL="https://github.com/${{ github.repository }}.git"

            # Check if the application directory exists.
            if [ -d "$APP_DIR" ]; then
              echo "Application directory exists. Pulling latest changes..."
              cd "$APP_DIR"
              git fetch origin main
              git reset --hard origin/main # Forcefully overwrite local changes
              git pull origin main
            else
              echo "Application directory not found. Cloning repository..."
              git clone "$REPO_URL" "$APP_DIR"
              cd "$APP_DIR"
            fi

            # Ensure run.sh is executable
            chmod +x run.sh

            echo "Running deployment script..."
            ./run.sh

            echo "Deployment successful!"
